// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Blockchain Transaction Parser API
 *
 * API for parsing and tracking blockchain transactions with subscription capabilities.
 *
 * API version: 1.0.0
 */

package httpinfragenerated

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
