// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Blockchain Transaction Parser API
 *
 * API for parsing and tracking blockchain transactions with subscription capabilities.
 *
 * API version: 1.0.0
 */

package httpinfragenerated

type BlockNumberResponse struct {

	// The latest block number processed by the parser
	BlockNumber int64 `json:"blockNumber,omitempty"`
}

// AssertBlockNumberResponseRequired checks if the required fields are not zero-ed
func AssertBlockNumberResponseRequired(obj BlockNumberResponse) error {
	return nil
}

// AssertBlockNumberResponseConstraints checks if the values respects the defined constraints
func AssertBlockNumberResponseConstraints(obj BlockNumberResponse) error {
	return nil
}
