// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Blockchain Transaction Parser API
 *
 * API for parsing and tracking blockchain transactions with subscription capabilities.
 *
 * API version: 1.0.0
 */

package httpinfragenerated

import (
	"time"
)

type Transaction struct {

	// Unique transaction identifier
	Id string `json:"id,omitempty"`

	BlockNumber int64 `json:"blockNumber,omitempty"`

	Source string `json:"source,omitempty" validate:"regexp=^0x[a-fA-F0-9]{40}$"`

	Destination string `json:"destination,omitempty" validate:"regexp=^0x[a-fA-F0-9]{40}$"`

	AmountInEther string `json:"amountInEther,omitempty" validate:"regexp=^\\\\d+\\\\.\\\\d+$"`

	FeesInEther string `json:"feesInEther,omitempty" validate:"regexp=^\\\\d+\\\\.\\\\d+$"`

	CreationDate time.Time `json:"creationDate,omitempty"`
}

// AssertTransactionRequired checks if the required fields are not zero-ed
func AssertTransactionRequired(obj Transaction) error {
	return nil
}

// AssertTransactionConstraints checks if the values respects the defined constraints
func AssertTransactionConstraints(obj Transaction) error {
	return nil
}
