// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Blockchain Transaction Parser API
 *
 * API for parsing and tracking blockchain transactions with subscription capabilities.
 *
 * API version: 1.0.0
 */

package httpinfragenerated

type SuccessResponse struct {
	Success bool `json:"success,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertSuccessResponseRequired checks if the required fields are not zero-ed
func AssertSuccessResponseRequired(obj SuccessResponse) error {
	return nil
}

// AssertSuccessResponseConstraints checks if the values respects the defined constraints
func AssertSuccessResponseConstraints(obj SuccessResponse) error {
	return nil
}
